FROM python:3.12-slim

WORKDIR /app

ENV DB_ADMIN=postgresql://fedor:postgrespass@postgres.markovfd-itmo.ru:5432/db

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY alembic.ini .
COPY migrations/ migrations/
COPY main.py models.py connection.py ./

EXPOSE 8080

# Миграция -> запуск FastAPI
CMD ["sh", "-c", "exec uvicorn main:app --host 0.0.0.0 --port 8080"]